//COMPONENT CONTROLLER
app.controller("BootstrapCtrl", function ($scope) {

    //BOOTSTRAP
    $scope.bootstrapContentA = true; //NAVBAR
    $scope.bootstrapContentB = false; //SIDEBAR
    $scope.bootstrapContentC = false; //ROWS AND COLUMS
    $scope.bootstrapContentD = false; //CONTAINERS
    $scope.bootstrapContentE = false; //JUMBOTRON
    $scope.bootstrapContentF = false; //TYPOGRAPHY
    $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
    $scope.bootstrapContentH = false; //QUICK FLOATS
    $scope.bootstrapContentI = false; //BLOCKQUOTE
    $scope.bootstrapContentJ = false; //CODE
    $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
    $scope.bootstrapContentL = false; //BUTTONS
    $scope.bootstrapContentM = false; //FORMS
    $scope.bootstrapContentN = false; //TABLES
    $scope.bootstrapContentO = false; //LIST
    $scope.bootstrapContentP = false; //PANELS
    $scope.bootstrapContentQ = false; //WELL
    $scope.bootstrapContentR = false; //ALERTS
    $scope.bootstrapContentS = false; //PROGESSBAR
    $scope.bootstrapContentT = false; //LABEL
    $scope.bootstrapContentU = false; //BADGES
    $scope.bootstrapContentV = false; //IMAGES


    $scope.BootstrapTab = function (tab) {
        if (tab == 'contentA') {
            $scope.bootstrapContentA = true; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentB') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = true; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentC') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = true; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentD') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = true; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentE') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = true; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentF') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = true; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentG') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = true; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentH') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = true; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentI') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = true; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentJ') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = true; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentK') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = true; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentL') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = true; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentM') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = true; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentN') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = true; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentO') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = true; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentP') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = true; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentQ') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = true; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentR') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = true; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentS') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = true; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentT') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = true; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentU') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = true; //BADGES
            $scope.bootstrapContentV = false; //IMAGES
        }
        else if (tab == 'contentV') {
            $scope.bootstrapContentA = false; //NAVBAR
            $scope.bootstrapContentB = false; //SIDEBAR
            $scope.bootstrapContentC = false; //ROWS AND COLUMS
            $scope.bootstrapContentD = false; //CONTAINERS
            $scope.bootstrapContentE = false; //JUMBOTRON
            $scope.bootstrapContentF = false; //TYPOGRAPHY
            $scope.bootstrapContentG = false; //ALIGNMENT AND TRANSFORMATION
            $scope.bootstrapContentH = false; //QUICK FLOATS
            $scope.bootstrapContentI = false; //BLOCKQUOTE
            $scope.bootstrapContentJ = false; //CODE
            $scope.bootstrapContentK = false; //CONTEXTUAL COLOR
            $scope.bootstrapContentL = false; //BUTTONS
            $scope.bootstrapContentM = false; //FORMS
            $scope.bootstrapContentN = false; //TABLES
            $scope.bootstrapContentO = false; //LIST
            $scope.bootstrapContentP = false; //PANELS
            $scope.bootstrapContentQ = false; //WELL
            $scope.bootstrapContentR = false; //ALERTS
            $scope.bootstrapContentS = false; //PROGESSBAR
            $scope.bootstrapContentT = false; //LABEL
            $scope.bootstrapContentU = false; //BADGES
            $scope.bootstrapContentV = true; //IMAGES
        }
    }

});